# DISCLAIMER:
# This manifest is not enabled or used by default, but here for disaster recovery situations.
# It is needed to generate Kubernetes VolumeSnapshot CRs from previously deployed VolumeSnapshotContent CRs
# Pay special attention to the 'volumeHandle' parameter in the VolumeSnapshotContent CRs: it must match cloud resources

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pgdata-keycloak-postgresql-cluster-0.yaml
  - pgdata-keycloak-postgresql-cluster-1.yaml
  - pgdata-keycloak-postgresql-cluster-2.yaml
