# DISCLAIMER:
# This manifest is not enabled or used by default, but here for disaster recovery situations.
# It is needed to generate Kubernetes VolumeSnapshot CRs from previously deployed VolumeSnapshotContent CRs
# Pay special attention to the 'volumeHandle' parameter in the VolumeSnapshotContent CRs: it must match cloud resources

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pgdata-keycloak-postgresql-cluster-1
spec:
  volumeSnapshotClassName: csi-block
  source:
    volumeSnapshotContentName: pgdata-keycloak-postgresql-cluster-1
