apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  # Craft the Secret resources using credentials from Vault for production environment
  - externalSecrets

  
