apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-keycloak-postgresql-cluster-2
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
