# Configuration: https://www.keycloak.org/server/all-config
# Logging: https://www.keycloak.org/server/logging

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-credentials
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: infrastructure/develop/keycloak/users/admin
        property: username

    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: infrastructure/develop/keycloak/users/admin
        property: password
