# Configuration: https://www.keycloak.org/server/all-config
# Logging: https://www.keycloak.org/server/logging

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-database-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: keycloak-database-credentials
  data:
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: infrastructure/develop/keycloak/postgresql/users/keycloak
        property: username

    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: infrastructure/develop/keycloak/postgresql/users/keycloak
        property: password
