apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "keycloak.name" . }}-credentials
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    roleName: keycloak-i0-production
    vaultAddress: https://vault.example.com
    vaultKubernetesMountPath: i0
    objects: |
      - secretPath: "apps_secrets/data/keycloak/i0/production/postgres/keycloak"
        secretKey: DATABASE_USERNAME
        objectName: postgres-username

      - secretPath: "apps_secrets/data/keycloak/i0/production/postgres/keycloak"
        secretKey: DATABASE_PASSWORD
        objectName: postgres-password

      - secretPath: "apps_secrets/data/keycloak/i0/production/postgres/keycloak"
        secretKey: DATABASE_ADDRESS
        objectName: postgres-address

      - secretPath: "apps_secrets/data/keycloak/i0/production/credentials"
        secretKey: admin-username
        objectName: admin-username

      - secretPath: "apps_secrets/data/keycloak/i0/production/credentials"
        secretKey: admin-password
        objectName: admin-password

  secretObjects:
    - secretName: keycloak-credentials
      type: Opaque
      data:
        # TODO
        - objectName: postgres-username
          key: KC_DB_USERNAME
        - objectName: postgres-password
          key: KC_DB_PASSWORD
        - objectName: postgres-address
          key: KC_DB_URL_HOST

        # TODO
        - objectName: admin-username
          key: KEYCLOAK_ADMIN
        - objectName: admin-password
          key: KEYCLOAK_ADMIN_PASSWORD


