apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app.kubernetes.io/name: keycloak

resources:
  # Deploy the OIDC
  - statefulSet-keycloak.yaml
  - service-keycloak.yaml

  # Deploy resources to be able to discover the pods
  - service-keycloak-jgroups.yaml
  - serviceAccount-keycloak.yaml
  - role-keycloak-pod-reader.yaml
  - roleBinding-keycloak-read-pods.yaml
