apiVersion: v1
kind: Service
metadata:
  name: keycloak-jgroups
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: jgroups
      port: 7800
      targetPort: 7800
      protocol: TCP
  selector: {}
  sessionAffinity: None
