global:
  env:
    # PosgreSQL related variables
    KC_DB: postgres
    KC_DB_URL_HOST: "postgresql.keycloak.svc"
    KC_DB_URL_PORT: "5432"
    KC_DB_URL_DATABASE: postgres
    KC_DB_USERNAME: postgres

    # Keycloak admin user related variables
    KEYCLOAK_ADMIN: admin

  secretEnv:
    # PosgreSQL related variables
    KC_DB_PASSWORD: postgres

    # Keycloak admin user related variables
    KEYCLOAK_ADMIN_PASSWORD: admin-placeholder

  postgresql:
    auth:
      existingSecret: "keycloak-global-env"
      secretKeys:
        adminPasswordKey: "KC_DB_PASSWORD"

# Ref: https://github.com/codecentric/helm-charts/blob/master/charts/keycloakx/values.yaml
keycloak:

  # Configuration for the keycloak chart itself
  fullnameOverride: keycloak

  # RBAC rules for KUBE_PING discovery of the cluster nodes
  rbac:
    create: true
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list

  # On develop environments, it is not needed to spread the pods across several nodes to enforce HA
  affinity: |

  # Deployment related parameters
  replicas: 3
  args: ["start", "--auto-build"]

  # Disable autoconfiguration of several parameters, to avoid hiding critical configuration
  # that affects the behaviour for Keycloak by this helm chart
  cache:
    stack: custom
  proxy:
    enabled: false
  metrics:
    enabled: false
  health:
    enabled: false

  # Populate configuration environment variables. This is the native way for Keycloak
  extraEnv: |
    # Cache parameters
    - name: KC_CACHE
      value: "ispn"
    - name: KC_CACHE_STACK
      value: "kubernetes"
    - name: JAVA_OPTS_APPEND
      value: "-Djgroups.dns.query=keycloak-headless.keycloak.svc"
    - name: CACHE_OWNERS_COUNT
      value: "3"
    - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
      value: "3"

    # Networking parameters
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_HOSTNAME
      value: keycloak.barbudeando.com
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_PROXY
      value: "edge"
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

    # Monitoring parameters
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"
    - name: KC_LOG
      value: console
    - name: KC_LOG_CONSOLE_OUTPUT
      value: json
    - name: KC_LOG_LEVEL
      value: info

  extraEnvFrom: |
    - secretRef:
        name: keycloak-global-env
    - configMapRef:
        name: keycloak-global-env

  ingress:
    enabled: false

# Ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  enabled: true
  fullnameOverride: "postgresql"
