apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-standby-user-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: standby.keycloak-postgresql-cluster.credentials.postgresql.acid.zalan.do
    template:
      # In this engine version they add the sprig functions and use string by default
      engineVersion: v2
      data:
        username: standby
        password: |
          {{- .PASSWORD -}}
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: infrastructure/production/keycloak/postgresql/users/standby
        property: password
