# DISCLAIMER:
# This manifest is not enabled or used by default, but here for disaster recovery situations, to know the spec
# needed to get a snapshot from AWS and generate the Kubernetes VolumeSnapshotContent at change.
# Pay special attention to the 'snapshotHandle' parameter, because it is there to match the cloud resource

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: pgdata-keycloak-postgresql-cluster-0
spec:
  deletionPolicy: Retain
  driver: ebs.csi.aws.com
  source:
    # Following ID is required to get the snapshot from the cloud provider.
    snapshotHandle: snap-xxxxxxxxxxxxxxxxx
  volumeSnapshotClassName: csi-block
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: pgdata-keycloak-postgresql-cluster-0
    namespace: keycloak
