apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  labels: &labels {}
spec:
  namespaceSelector:
    matchNames:
      - keycloak
  selector:
    matchLabels: *labels
  endpoints:
    - targetPort: 8080
      path: /metrics
      interval: 5s
      scrapeTimeout: 5s
