site_name: Keycloak
site_url: https://github.com/achetronic/keycloak-in-kubernetes

markdown_extensions:
  # Beautiful different types of notes.
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition

nav:
  - Overview: README.md
  - Security Model: security-model.md
  - FAQ: faq.md
